### ISSUE TITLE
empty screen

### ISSUE THREAD

**Issue by dyipon** [groundcover-com/murre#5]
hello,

I just installed and started murre, but I just get an empty screen. Whats the best way to debug this issue?

**Comment by larssb** [comment]
Provide your environment details.

- go version
- shell you're in
- system you're using
- the version of said system

and on you go.

---

I also had an empty screen initially. Then waited a bit and here it goes ....

Suggestion: Try sizing the screen/window of your shell/terminal and see if that refreshes and gives the content that `murre` outputs.

**Comment by dyipon** [comment]
im using latest murre, go version go1.18.3 linux/amd64, and debian/bash

**Comment by LarsBingBong** [comment]
Did you try my suggestion ... sizing the terminal window?

**Comment by dyipon** [comment]
tried, did not help :/

**Comment by ulrichSchreiner** [comment]
hi,
i have the same bug. it looks like you use ~/.kube/config as default although i have a `$KUBECONFIG` environment setting. when starting murre with `murre --kubeconfig $KUBECONFIG` it works

**Comment by larssb** [comment]
Uuuh that's interesting @ulrichSchreiner - That's the same scenario I'm in ( using `--kubeconfig` ) - So that's  likely why I haven't bumped into it.

**Comment by maxlevinps** [comment]
> hi, i have the same bug. it looks like `murre` uses ~/.kube/config as default although i have a `$KUBECONFIG` environment setting. when starting murre with `murre --kubeconfig $KUBECONFIG` it works

Hey @ulrichSchreiner - we've created a fix for the env support which be added in our next release

**Comment by dyipon** [comment]
@maxlevinps I just updated to 0.0.3, and tried again:
```bash
$ murre --kubeconfig ~/.kube/config  
```

but still nothing, I just get empty screen

**Comment by ulrichSchreiner** [comment]
do you have a correct (working) `~/.kube/config` . you do not need to specify this config as this is the default. 

i use [kubie](https://github.com/sbstp/kubie) to manage different cluster configs and kubie creates temporary files with a config and sets `KUBECONFIG` to this file. the people here  fixed their code, so with the latest version of `murre` one can now use the environment setting wthout using the `--kubeconfig` parameter.

in my case i do have  a file `~/.kube/config`  but it points to a minikube which is not running, so neither `kubectl` nor `murre` can connect and hang silently. so can you simple test `kubectl get nodes` to see if you have a running cluster and your default config works?

**Comment by dyipon** [comment]
don't know why, but it's started to working.

**Comment by giuliohome** [comment]
Maybe can we reopen the issue and double check what happens in my case too?

```
[giulio@fedora ~]$ cat /etc/fedora-release
Fedora release 37 (Thirty Seven)
[giulio@fedora ~]$ cat /proc/version
Linux version 6.0.11-300.fc37.x86_64 (mockbuild@bkernel01.iad2.fedoraproject.org) (gcc (GCC) 12.2.1 20221121 (Red Hat 12.2.1-4), GNU ld version 2.38-25.fc37) #1 SMP PREEMPT_DYNAMIC Fri Dec 2 20:47:45 UTC 2022
```

and

```
[giulio@fedora ~]$ minikube start
😄  minikube v1.28.0 on Fedora 37
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔄  Restarting existing docker container for "minikube" ...
🐳  Preparing Kubernetes v1.25.3 on Docker 20.10.20 ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
    ▪ Using image docker.io/kubernetesui/dashboard:v2.7.0
    ▪ Using image docker.io/kubernetesui/metrics-scraper:v1.0.8
💡  Some dashboard features require the metrics-server addon. To enable all features please run:

	minikube addons enable metrics-server	


🌟  Enabled addons: default-storageclass, storage-provisioner, dashboard
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
[giulio@fedora ~]$ 
```

and my pods

```
[giulio@fedora ~]$ kubectl get pod
NAME                              READY   STATUS    RESTARTS        AGE
gke-golang-web-68d985fb4b-g62j5   1/1     Running   1 (4m25s ago)   112m
gke-golang-web-68d985fb4b-mwrvl   1/1     Running   1 (4m24s ago)   112m
postgres-statefulset-0            1/1     Running   1 (4m24s ago)   3h51m
```

Finally

`[giulio@fedora ~]$ murre --sortby-cpu-utilization
`

![image](https://user-images.githubusercontent.com/3272563/206004824-983505bc-585f-4ecb-9ced-18b257ea79a5.png)

**Comment by giuliohome** [comment]
Tried with Lens, which is very smart and suggested me to install prometheus operator and the metric server



![image](https://user-images.githubusercontent.com/3272563/206009705-7d61b91e-d5cd-4c43-aa65-d08ef04ba412.png)
```

[giulio@fedora ~]$ helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update
"prometheus-community" has been added to your repositories
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "prometheus-community" chart repository
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
[giulio@fedora ~]$ helm install myprometheus prometheus-community/kube-prometheus-stack
NAME: myprometheus
LAST DEPLOYED: Tue Dec  6 20:48:20 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
kube-prometheus-stack has been installed. Check its status by running:
  kubectl --namespace default get pods -l "release=myprometheus"

Visit https://github.com/prometheus-operator/kube-prometheus for instructions on how to create & configure Alertmanager and Prometheus instances using the Operator.
[giulio@fedora ~]$ helm repo add metrics-server https://kubernetes-sigs.github.io/metrics-server/
"metrics-server" has been added to your repositories
[giulio@fedora ~]$ helm upgrade --install metrics-server metrics-server/metrics-server
Release "metrics-server" does not exist. Installing it now.
NAME: metrics-server
LAST DEPLOYED: Tue Dec  6 20:53:03 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
***********************************************************************
* Metrics Server                                                      *
***********************************************************************
  Chart version: 3.8.2
  App version:   0.6.1
  Image tag:     k8s.gcr.io/metrics-server/metrics-server:v0.6.1
***********************************************************************
[giulio@fedora ~]$ 
```

**Comment by giuliohome** [comment]
I've cloned the repo and built it after adding some fmt.Println to understand the flow.
I can't see this in the output, so the issue is that this isn't called

```
func (t *Table) getCell(stats *k8s.Stats, column int) *tview.TableCell {
        fmt.Println("stats",stats.Namespace, stats.PodName, stats.ContainerName)
```

even if I see the tick e the output before updateMetric

```
        fmt.Println("update Metrics!")
        err = m.updateMetrics()
```

I guess something goes wrong in between.

Thank you for your help
